import type { ServiceTypeOption } from "../types";

export const SERVICE_TYPE_OPTIONS: ServiceTypeOption[] = [
  {
    type: 'TRADITIONAL_BURIAL',
    name: 'Traditional Burial',
    description: 'Full service funeral with viewing, ceremony, and burial. Includes embalming, casket selection, and cemetery arrangements.',
    basePrice: 8500,
    icon: '⚰️',
    features: [
      'Embalming and preparation',
      'Viewing and visitation',
      'Funeral ceremony',
      'Casket selection',
      'Cemetery services',
      'Memorial cards',
    ],
  },
  {
    type: 'TRADITIONAL_CREMATION',
    name: 'Traditional Cremation',
    description: 'Full service funeral with viewing and ceremony followed by cremation. Includes embalming, ceremony, and urn selection.',
    basePrice: 6500,
    icon: '🕯️',
    features: [
      'Embalming and preparation',
      'Viewing and visitation',
      'Funeral ceremony',
      'Cremation services',
      'Urn selection',
      'Memorial cards',
    ],
  },
  {
    type: 'MEMORIAL_SERVICE',
    name: 'Memorial Service',
    description: 'Ceremony without the body present, typically after cremation or burial has occurred. Focus on celebration of life.',
    basePrice: 3500,
    icon: '🌸',
    features: [
      'Memorial ceremony',
      'Photo displays',
      'Guest book',
      'Memorial cards',
      'Reception coordination',
    ],
  },
  {
    type: 'DIRECT_BURIAL',
    name: 'Direct Burial',
    description: 'Simple burial service without viewing or ceremony. Cost-effective option with immediate interment.',
    basePrice: 3000,
    icon: '🪦',
    features: [
      'Basic services',
      'Transportation',
      'Simple casket',
      'Cemetery coordination',
      'Death certificates',
    ],
  },
  {
    type: 'DIRECT_CREMATION',
    name: 'Direct Cremation',
    description: 'Simple cremation without viewing or ceremony. Most cost-effective option with immediate cremation.',
    basePrice: 2500,
    icon: '🔥',
    features: [
      'Basic services',
      'Transportation',
      'Cremation container',
      'Cremation services',
      'Basic urn',
      'Death certificates',
    ],
  },
  {
    type: 'CELEBRATION_OF_LIFE',
    name: 'Celebration of Life',
    description: 'Personalized memorial service focused on celebrating the unique life and legacy of your loved one.',
    basePrice: 4000,
    icon: '🎉',
    features: [
      'Personalized ceremony',
      'Venue coordination',
      'Photo/video displays',
      'Memorial keepsakes',
      'Reception planning',
      'Memory sharing',
    ],
  },
];
