import { Effect } from 'effect';
import { GoEmployeeOnboardingPort, type GoEmployeeOnboardingPortService, NetworkError } from '../../ports/go-employee-onboarding-port';

/**
 * Use Case 4.1: Employee Onboarding Workflow
 * 
 * **Workflow**:
 * 1. Create new hire employee record
 * 2. Generate onboarding checklist (I-9, W-4, benefits enrollment, etc.)
 * 3. Track completion status
 * 4. Generate status report
 * 
 * **Business Rules**:
 * - Employee must have valid hire date
 * - Position and department must be specified
 * - Standard onboarding tasks are generated automatically
 * 
 * **Error Cases**:
 * - NetworkError: Go backend communication failure
 * 
 * @see docs/Implement 35 Critical Use Cases with Verified Go Backend Ports.md - Phase 5, Use Case 4.1
 */

/**
 * Employee Onboarding
 *
 * Policy Type: Type B
 * Refactoring Status: 🔴 HARDCODED
 * Policy Entity: N/A
 * Persisted In: N/A
 * Go Backend: YES
 * Per-Funeral-Home: YES
 * Test Coverage: 0 tests
 * Last Updated: N/A
 */

export interface EmployeeOnboardingCommand {
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
  readonly hireDate: Date;
  readonly positionId: string;
  readonly positionTitle: string;
  readonly department: string;
  readonly terminationDate?: Date;
}

export interface EmployeeOnboardingResult {
  readonly onboardingId: string;
  readonly employeeId: string;
  readonly employeeNumber: string;
  readonly fullName: string;
  readonly hireDate: Date;
  readonly tasksTotal: number;
  readonly tasksCompleted: number;
  readonly tasksRemaining: number;
  readonly status: 'in_progress' | 'completed';
  readonly tasks: ReadonlyArray<{
    readonly id: string;
    readonly name: string;
    readonly completed: boolean;
    readonly completedAt?: Date;
  }>;
}

export const startEmployeeOnboarding = (
  command: EmployeeOnboardingCommand
) =>
  Effect.gen(function* () {
    const onboardingPort = yield* GoEmployeeOnboardingPort;

    // Step 1: Create new hire employee record
    const employee = yield* onboardingPort.hireEmployee({
      firstName: command.firstName,
      lastName: command.lastName,
      email: command.email,
      hireDate: command.hireDate,
      terminationDate: command.terminationDate,
      positionId: command.positionId,
      positionTitle: command.positionTitle,
      department: command.department,
    });

    // Step 2: Get onboarding checklist (auto-generated by backend)
    const onboardingTasks = yield* onboardingPort.getOnboardingTasks(employee.id);

    // Step 3: Calculate completion status
    const tasksCompleted = onboardingTasks.filter(task => task.completed).length;
    const tasksRemaining = onboardingTasks.length - tasksCompleted;
    const status = tasksRemaining === 0 ? 'completed' : 'in_progress';

    return {
      onboardingId: employee.id, // Use employee ID as onboarding ID
      employeeId: employee.id,
      employeeNumber: employee.employeeNumber,
      fullName: `${employee.firstName} ${employee.lastName}`,
      hireDate: employee.hireDate,
      tasksTotal: onboardingTasks.length,
      tasksCompleted,
      tasksRemaining,
      status,
      tasks: onboardingTasks.map(task => ({
        id: task.id,
        name: task.name,
        completed: task.completed,
        completedAt: task.completedAt,
      })),
    };
  }).pipe(
    Effect.withSpan('startEmployeeOnboarding', {
      attributes: {
        firstName: command.firstName,
        lastName: command.lastName,
        email: command.email,
        hireDate: command.hireDate.toISOString(),
        department: command.department,
      },
    })
  );

/**
 * Type helper for the Effect return
 */
export type EmployeeOnboardingEffect = Effect.Effect<
  EmployeeOnboardingResult,
  NetworkError,
  GoEmployeeOnboardingPortService
>;
