import { z } from 'zod';
import { emailSchema } from './shared-schemas';

/**
 * Employee Validation Schemas
 * 
 * Schemas for employee management including hiring, updates, and onboarding.
 */

// Employee status enum
export const EMPLOYEE_STATUSES = ['active', 'onboarding', 'on_leave', 'offboarding', 'terminated'] as const;

// Department enum
export const DEPARTMENTS = ['Operations', 'Finance', 'Admin', 'Other'] as const;

// Position/Title enum (common roles in funeral homes)
export const POSITION_TITLES = [
  'Funeral Director',
  'Embalmer',
  'Staff Member',
  'Driver',
  'Accountant',
  'Office Manager',
  'Receptionist',
  'Pre-Need Counselor',
  'Other',
] as const;

/**
 * Schema for hiring a new employee
 * Used in Add Employee Modal and employee onboarding
 */
export const hireEmployeeSchema = z.object({
  firstName: z.string().min(1, 'First name is required').max(255, 'First name must be less than 255 characters').trim(),
  lastName: z.string().min(1, 'Last name is required').max(255, 'Last name must be less than 255 characters').trim(),
  email: emailSchema,
  hireDate: z.date({
    required_error: 'Hire date is required',
    invalid_type_error: 'Invalid hire date',
  }),
  positionTitle: z.string().min(1, 'Position title is required'),
  department: z.enum(DEPARTMENTS, {
    required_error: 'Department is required',
    invalid_type_error: 'Invalid department',
  }),
  // Optional: will be generated by backend if not provided
  positionId: z.string().optional(),
});

export type HireEmployeeInput = z.infer<typeof hireEmployeeSchema>;

/**
 * Schema for updating employee information
 */
export const updateEmployeeInfoSchema = z.object({
  email: emailSchema.optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
  emergencyContact: z.string().max(255, 'Emergency contact must be less than 255 characters').trim().optional(),
  emergencyPhone: z.string().optional(),
});

export type UpdateEmployeeInfoInput = z.infer<typeof updateEmployeeInfoSchema>;

/**
 * Schema for employee termination
 */
export const terminateEmployeeSchema = z.object({
  terminationDate: z.date({
    required_error: 'Termination date is required',
  }),
  reason: z.string().min(10, 'Reason must be at least 10 characters'),
  eligibleForRehire: z.boolean().default(true),
});

export type TerminateEmployeeInput = z.infer<typeof terminateEmployeeSchema>;
